### ISSUE TITLE
Unused reducer

### ISSUE THREAD

**Issue by parkjoon** [monikaphogat4/milestone2#3]
https://github.com/monikaphogat4/milestone2/blob/dcaba452b2bb9f79a7caaf2049c49e876a472456/redux/reducers/sectionReducer.js#L34-L39
^ This reducer just sets the initial state with the hardcoded sections. Instead, you should use the ADD_SECTION action you built to set the state inside a componentDidMount

**Comment by parkjoon** [comment]
example: https://stackoverflow.com/questions/46564941/react-redux-how-to-dispatch-an-action-on-componentdidmount-when-using-mapdispa
^ this example uses a fetch (api request), but yours wouldn't need to do that. the function for ADD_SECTION can just be called addSection (or similar)

**Comment by monikaphogat4** [comment]
Added change to set state in componentDidMount on action.
