### ISSUE TITLE
remove unnecessary empty string?

### ISSUE THREAD

**Issue by parkjoon** [monikaphogat4/milestone2#9]
https://github.com/monikaphogat4/milestone2/blob/dcaba452b2bb9f79a7caaf2049c49e876a472456/components/MainImage.js#L129

^ can you remove unnecessary empty string? not 100% sure if your ref text change will  work if you remove though. can you check please

**Comment by monikaphogat4** [comment]
Removed empty string and tested, on scroll text change works as expected.
